{ testers, site }:
testers.lycheeLinkCheck {
  inherit site;
  # TODO: https://github.com/NixOS/nixpkgs/pull/520792
  # relocatable = true;
  extraConfig = {
    # 404.html is generated by mdBook but unused on nixops.dev;
    # it contains a root-relative link that fails the relocatable check.
    exclude_path = [ "404\\.html" ];
  };
}
