name: Build

on:
  pull_request: {}
  push:
    branches:
      - integration

jobs:
  build:
    name: Build
    permissions:
      id-token: "write"
      contents: "read"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix build -L
